version: '2'

services:
  config:
      image: liumapp/docker-config:v1.0.0
  config:
      image: liumapp/docker-config:v1.0.0
  peer2:
      image: liumapp/server-maven:v1.0.0
      hostname: peer2
      ports:
        - "12346:12346"
      environment:
        - spring.profiles.active=peer2
  peer1:
      image: liumapp/server-maven:v1.0.0
      ports:
        - "12345:12345"
      environment:
        - spring.profiles.active=peer1
