spring:
  application:
    name: server-profile
---
spring:
  profiles: peer1
server:
  port: 12345
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:12346/eureka/
---
spring:
  profiles: peer2
server:
  port: 12346
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:12345/eureka/

