version: '2'
services:
  peer1:
    image: liumapp/server-maven:v1.0.0
    ports:
      - "12345:12345"
    environment:
      - spring.profiles.active=peer1
  peer2:
    image: liumapp/server-maven:v1.0.0
    hostname: peer2
    ports:
      - "12346:12346"
    environment:
      - spring.profiles.active=peer2